# Generated by Django 5.0.1 on 2024-01-18 10:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question2',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=64, primary_key=True, serialize=False)),
                ('data', models.TextField()),
                ('answer', models.TextField()),
                ('prompt', models.TextField()),
                ('hashPrompt', models.CharField(db_index=True, max_length=64)),
                ('embedding', models.TextField()),
            ],
            options={
                'db_table': 'question2',
            },
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
