# Generated by Django 5.0.1 on 2024-01-19 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question2', '0002_question2_delete_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question2',
            name='embedding',
            field=models.JSONField(),
        ),
    ]
