# Generated by Django 5.0.1 on 2024-01-18 02:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("data", models.JSONField()),
                ("prompt", models.TextField()),
                ("documentID", models.CharField(db_index=True, max_length=64)),
                ("hashPrompt", models.CharField(db_index=True, max_length=64)),
                ("rating", models.SmallIntegerField(default=0)),
                ("active", models.BooleanField(default=True)),
                ("embedding", models.JSONField()),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
